include brew path; remove rbenv

diff --git a/run_once_after_install-packages.sh.tmpl b/run_once_after_install-packages.sh.tmpl
--- a/run_once_after_install-packages.sh.tmpl
+++ b/run_once_after_install-packages.sh.tmpl
@@ -1,8 +1,13 @@
 {{ if eq .chezmoi.os "darwin" -}}
-#!/bin/sh
+#!/bin/zsh
+source ~/.zprofile
+source ~/.zshenv
+source ~/.zshrc
+
 # brew
 brew bundle install || echo "Brew installation failed"
 brew tap homebrew/cask-fonts && brew install font-hack-nerd-font || echo "Brew installation of Nerd Font failed"
+sudo chown -R $(whoami) $(brew --prefix)/* || echo "failed to change owner of brew folders"
 
 # n, npm, node
 curl -L https://bit.ly/n-install | bash -s -- -y || echo "n installation failed"
